version: "3"
#
#
services:
  # - Golang
  app:
    container_name: meal-go
    build: ./app
    volumes:
      - ../:/go/src/
    networks:
      - meal-front-end
      - meal-back-end
  # - Postgres
  database:
    container_name: meal-postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres.
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./database/fill.sql:/docker-entrypoint-initdb.d/fill.sql
    networks:
      - meal-back-end
    ports:
      - 5432:5432
  # - Nginx
  web:
    container_name: meal-nginx
    image: nginx
    restart: always
    volumes:
      - ../internal/nginx/html:/usr/share/nginx/html
      - ../internal/nginx/conf:/etc/nginx/conf.d
    networks:
      - meal-front-end
    ports:
      - 8080:80
#
#
volumes:
  db-data:
    driver: local
#
#
networks:
  # The presence of these objects is sufficient to define them
  meal-front-end: {}
  meal-back-end: {}