version: '3.3'

services:
  # - Golang
  app:
    container_name: meal-go
    build: ./app
    volumes:
      - ../:/go/src/
    networks:
      - meal-front-end
      - meal-back-end
  # - Postgres
  database:
    container_name: meal-postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: chef
      POSTGRES_PASSWORD: cooking123
      POSTGRES_DB: mymeals
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
      - ./database/populate.sql:/docker-entrypoint-initdb.d/docker_postgres_populate.sql
    networks:
      - meal-back-end
    ports:
      - "5432:5432"
  # - PG-Admin
  admin:
    container_name: meal-postgres-admin
    image: dpage/pgadmin4
    environment: 
        PGADMIN_DEFAULT_EMAIL: "chef@mymeal.com"
        PGADMIN_DEFAULT_PASSWORD: "cooking123"
    networks:
      - meal-back-end
    ports: 
        - "2345:80"
    depends_on:
        - database
  # - Nginx
  web:
    container_name: meal-nginx
    image: nginx
    restart: always
    volumes:
      - ../internal/nginx/html:/usr/share/nginx/html
      - ../internal/nginx/conf:/etc/nginx/conf.d
    networks:
      - meal-front-end
    ports:
      - "8080:80"
    depends_on:
      - app
      - database

volumes:
  db-data:
    driver: local

networks:
  # The presence of these objects is sufficient to define them
  meal-front-end: {}
  meal-back-end: {}