CREATE TABLE  "MEALS" 
(
    "MEAL_ID" CHAR(6) NOT NULL PRIMARY KEY, 
    "MEAL_NAME" CHAR(40) NOT NULL PRIMARY KEY, 
    "" CHAR(35), 
    "COMMISSION" NUMBER(10,2), 
    "PHONE_NO" CHAR(15), 
    "COUNTRY" VARCHAR2(25) 
);